name: digest_update

on:
  schedule:
    - cron: "15 */3 * * *"
permissions:
  contents: read
jobs:
  image-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: chainguard-dev/actions/digesta-bot@24611e635342e8de543de63dfcf569ad32fbb962
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
