name: digest_update

on:
  schedule:
    - cron: "15 */3 * * *"
permissions:
  contents: read
jobs:
  image-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # v3.3.0
    - name: Update Digest
      uses: chainguard-dev/actions/digesta-bot@24611e635342e8de543de63dfcf569ad32fbb962
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
