name: push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: ./.github/workflows/test.yaml
