name: slsa_provenance_create

on:
  workflow_call:
    inputs:
      image_digest:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string
      auth_provider:
        description: 'OIDC provider ID'
        required: true
        type: string
      auth_user:
        description: 'OIDC user ID'
        required: true
        type: string

permissions:
  contents: read

jobs:

  conf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image: ${{ steps.conf.outputs.image }}
      digest: ${{ steps.conf.outputs.digest }}
    steps:
    - name: Export Config
      id: conf
      run: |
        echo "image=$(echo ${{ inputs.image_digest }} | cut -d@ -f1)" >> $GITHUB_OUTPUT
        echo "digest=$(echo ${{ inputs.image_digest }} | cut -d@ -f2)" >> $GITHUB_OUTPUT

  provenance:
    needs:
    - conf
    permissions:
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.5.0
    with:
      image: ${{ needs.conf.outputs.image }}
      digest: ${{ needs.conf.outputs.digest }}
      registry-username: ${{ github.actor }}
      gcp-workload-identity-provider: ${{ inputs.auth_provider }}
      gcp-service-account: ${{ inputs.auth_user }}

  verify:
    needs:
    - provenance
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    steps:

    - name: Get Version
      run: |-
        set -euo pipefail
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "REG_URI=$(echo ${{ inputs.image_digest }} | cut -d/ -f1)" >> $GITHUB_ENV

    - uses: slsa-framework/slsa-verifier/actions/installer@v2.0.1

    - id: auth
      name: Auth GCP
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d  # v1.0.0
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.auth_provider }}
        service_account: ${{ inputs.auth_user }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1

    # slsa-verifier verify-image without the --provenance-path option fails with:
    # FAILED: SLSA verification failed: cannot retrieve sha256 of image: crane.Digest():
    # GET https://us-west1-docker.pkg.dev/v2/token?scope=repository%3Acloudy-s3c%2Fs3cme%2Fs3cme%3Apull&service=:
    # DENIED: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource
    # "projects/cloudy-s3c/locations/us-west1/repositories/s3cme" (or it may not exist)
    - name: Download SLSA Provenance
      run: |-
        gcloud auth configure-docker ${{ env.REG_URI }}
        gcloud artifacts docker images describe ${{ inputs.image_digest }} \
          --format json \
          --show-provenance > provenance.json

    - name: Verify SLSA Provenance
      run: |-
        set -euo pipefail
        slsa-verifier verify-image ${{ inputs.image_digest }} \
          --provenance-path provenance.json \
          --source-uri https://github.com/mchmarny/s3cme \
          --source-tag ${{ env.RELEASE_VERSION }}
