name: slsa_provenance_verification

on:
  workflow_call:
    inputs:
      image_digest:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string
      auth_provider:
        description: 'OIDC provider ID'
        required: true
        type: string
      auth_user:
        description: 'OIDC user ID'
        required: true
        type: string
      cosign_version:
        description: 'The version of cosign to use'
        required: false
        type: string
        default: 'v1.13.1'

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
    steps:

    - name: Checkout Code
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0

    - id: auth
      name: Auth GCP
      uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d  # v1.0.0
      with:
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.auth_provider }}
        service_account: ${{ inputs.auth_user }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b  # v2.8.1
      with:
        cosign-release: ${{ inputs.cosign_version }}

    - name: Auth Cosign
      env:
        REG_URI: $(echo ${{ inputs.image_digest }} | cut -d/ -f1)
      run: |
        set -euo pipefail
        cosign version
        cosign login "${REG_URI}" --username=oauth2accesstoken --password=${{ steps.auth.outputs.access_token }}

    - name: Verify Image SLSA Provenance
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        set -euo pipefail
        cosign verify-attestation \
          --type slsaprovenance \
          --policy policy/provenance.cue \
          ${{ inputs.image_digest }}
